name: handlebars
description: A wrapper for the Handlebars.js library.
version: 0.2.0
author: Fluidic Team <dev@fluidic.io>
homepage: https://github.com/fluidic/handlebars.dart

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  js: '>=0.6.0 <0.7.0'

dev_dependencies:
  browser: ^0.10.0+2
  test: '>=0.12.0 <0.13.0'
